config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :todos

  root 'todos#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
  	@todos = Todo.where("state = 'Pending'")
  end

  def new
  	@todo = Todo.new
  end

  def create
  	@todo = Todo.new(todo_params)

  	if @todo.save
        redirect_to todos_path
	 else
	    render 'new'	   
	 end
  end

  def update
    @todo = Todo.find_by(id: params[:id])
  	
  	if @todo.update_attributes(todo_params)
        redirect_to todos_path
        flash[:success]='Task marked as done'
  	else
  	    redirect_to todos_path	   
  	end
  end



  private

  def todo_params
  	params.require(:todo).permit(:description, :state)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/todos/index.html.erb
<h2>To Do's</h2>

<% if @todos.empty? %>
	<p>All Done!</p>
<%else %>
	<ul>
	<% @todos.each do |item| %>
		<li><%= item.description %> <%= button_to "Done!", todo_path(item.id),params: {'todo[state]' => 'Done'}, :method => :patch %> </li>
	<% end %>
	</ul>	
<% end %>

<%= link_to "Add item", new_todo_path %>

app/views/todos/new.html.erb
<%= form_for(@todo) do |f|%>
	<%= f.hidden_field :state, :value => 'Pending' %>	
	Remind me to...
	<%= f.text_field :description %>

	<%= f.submit %>
<% end %>